### ISSUE TITLE
[BUG] Pulsar cloud storage connector can't convert PROTO_NATIVE schema to Parquet schema

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-io-cloud-storage#268]
**Describe the bug**

The sink connector is not available to read topics with the `PROTO_NATIVE` schema.

The exception will be thrown:

```
19:04:35.029 [pulsar-io-cloud-storage-sink-flush-0] ERROR org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink - Caught unexpected exception:    org.apache.avro.SchemaParseException: Cannot parse <null> schema
        at org.apache.avro.Schema.parse(Schema.java:1633) ~[java-instance.jar:?]
        at org.apache.avro.Schema$Parser.parse(Schema.java:1430) ~[java-instance.jar:?]
        at org.apache.avro.Schema$Parser.parse(Schema.java:1418) ~[java-instance.jar:?]
        at org.apache.pulsar.io.jcloud.util.AvroRecordUtil.convertToAvroSchema(AvroRecordUtil.java:103) ~[qg2KQyXZ9-7y9GGaCCq0Hg/:?]
        at org.apache.pulsar.io.jcloud.format.ParquetFormat.initSchema(ParquetFormat.java:63) ~[qg2KQyXZ9-7y9GGaCCq0Hg/:?]
        at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.unsafeFlush(BlobStoreAbstractSink.java:239) ~[qg2KQyXZ9-7y9GGaCCq0Hg/:?]
        at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.flush(BlobStoreAbstractSink.java:219) ~[qg2KQyXZ9-7y9GGaCCq0Hg/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**

1. Create a topic with `PROTO_NATIVE` schema
2. Create a sink connector to read from the topic
3. The sink connector will fail

**Expected behavior**

The sink connector should read from topics with protobbuf or protobuf_native schema.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by freeznet** [comment]
The PR has been cherry-picked into 2.8, 2.9 and 2.10 branch, and will release with next weekly release.

**Comment by freeznet** [comment]
The PR has been verified locally and with sn-tests https://github.com/streamnative/streamnative-tests/pull/719
Cherry-picked into branch 2.8.2, 2.9.2, 2.10.0, and wait for release.
