### ISSUE TITLE
[BUG] formatType not working as expected

### ISSUE THREAD

**Issue by raviMoengage** [streamnative/pulsar-io-cloud-storage#488]
**Describe the bug**

We are using `pulsar-io-cloud-storage` connector for pushing pulsar topics' data into S3.

Then it gets an error stack as

```
2022-11-08T13:14:48,012+0000 [pulsar-io-cloud-storage-sink-flush-0] INFO  org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink - Flushing 10 buffered records to blob store
2022-11-08T13:14:48,012+0000 [pulsar-io-cloud-storage-sink-flush-0] ERROR org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink - Caught unexpected exception:
java.lang.NullPointerException: null
        at org.apache.pulsar.io.jcloud.util.AvroRecordUtil.recoverGenericSchemaFromInternalSchema(AvroRecordUtil.java:98) ~[2Wt2FL2iQu7JDGE6nzDX_g/:?]
        at org.apache.pulsar.io.jcloud.util.AvroRecordUtil.getPulsarSchema(AvroRecordUtil.java:82) ~[2Wt2FL2iQu7JDGE6nzDX_g/:?]
        at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.unsafeFlush(BlobStoreAbstractSink.java:250) ~[2Wt2FL2iQu7JDGE6nzDX_g/:?]
        at org.apache.pulsar.io.jcloud.sink.BlobStoreAbstractSink.flush(BlobStoreAbstractSink.java:216) ~[2Wt2FL2iQu7JDGE6nzDX_g/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**

1. pulsar-io-s3.yaml
```
tenant: "default"
namespace: "sample"
name: "pulsar-io-s3-test"
inputs:
  - "persistent://default/sample/topic-sink"
archive: "connectors/pulsar-io-cloud-storage-2.9.3.15.nar"
parallelism: 1
configs:
  provider: "aws-s3"
  accessKeyId: ""
  secretAccessKey: ""
  roleSessionName: "test"
  formatType: "bytes"
  bucket: "pulsar-bucket"
  pathPrefix: "pulsar/test/"
  region: "us-east-1"
  partitionerType: "time"
  timePartitionPattern: "yyyy-MM-dd"
  timePartitionDuration: "1d"
  batchSize: 10
  batchTimeMs: 1000
```

2. Local run is used for executing it on a pulsar broker
```
./bin/pulsar-admin sink localrun --sink-config-file conf/pulsar-io-s3.yaml
```

**Expected behavior**

`pulsar-io-cloud-storage` connector should be able to process the message and store it in the s3 bucket

**Additional context**
1. Function context is used for producing events into `persistent://default/sample/topic-sink` topic.
```
context.publish(f"persistent://default/sample/topic-sink", item, compression_type=_pulsar.CompressionType.LZ4, message_conf={"partition_key": context.get_partition_key()})
```

2. The messages in `persistent://default/sample/topic-sink` topic are of format `b'`, here is a sample message -
```
b'{"op":"u","ts_ms":1667798064000,"source":{"version":"0.8.0-SNAPSHOT","name":"sample"},"after":null}'
```

**Comment by raviMoengage** [comment]
We tried the function-mesh approach on Kubernetes, it is working. The `typeClassName` is set to `org.apache.pulsar.client.api.schema.GenericRecord`

  
```yaml  
apiVersion: compute.functionmesh.io/v1alpha1  
kind: Sink  
metadata:  
  name: pulsar-io-s3-sink  
  namespace: default  
spec:  
  image: streamnative/pulsar-io-cloud-storage:2.10.1.10  
  className: org.apache.pulsar.io.jcloud.sink.CloudStorageGenericRecordSink  
  replicas: 1  
  input:  
    topics:  
      - persistent://default/sample/topic-sink  
    typeClassName: "org.apache.pulsar.client.api.schema.GenericRecord"          
  sinkConfig:  
    provider: "aws-s3"  
    bucket: "pulsar-bucket"  
    region: "us-east-1"  
    accessKeyId: ""  
    secretAccessKey: ""  
    role: "test-role"  
    roleSessionName: "pulsar-io-s3"  
    formatType: "json"  
    partitionerType: "time"  
    timePartitionPattern: "yyyy-MM-dd"  
    timePartitionDuration: "1d"  
    batchSize: 2  
    batchTimeMs: 1000  
  pulsar:  
    pulsarConfig: "pulsar-function-mesh-config"  
  resources:  
    limits:  
      cpu: "0.2"  
      memory: 1.1G  
    requests:  
      cpu: "0.1"  
      memory: 1G  
  java:  
    jar: connectors/pulsar-io-cloud-storage-2.10.1.10.nar  
  clusterName: pulsar  
   
```  
  
Closing the issue.
